# Generated by Django 5.0.6 on 2024-07-05 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 7, 5, 13, 44, 11, 197279, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
